##PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_gateway
    username: postgres
    password: bintang123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
# Templates reloading during development
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    #    prefix: ${project.basedir}/src/main/resources/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  devtools:
    livereload:
      enabled: true
    add-properties: true
  resources:
    static-locations: file:src/main/resources/static/
    #    static-locations: ${project.basedir}/src/main/resources/static/
    cache:
      period: 0

## Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.show-sql=true

# spring.security.user.password=12345

# spring.datasource.initialization-mode=always
# spring.datasource.schema=classpath:/schema.sql
# spring.datasource.continue-on-error=true
# spring.thymeleaf.cache=false 
